---
title: "Práctica 1. Nociones de Bash y alineamientos básicos"
lang: es
date: today
execute: 
  output: true
  error: true
engine: knitr
bibliography: ../../doc/references.bib
language:
   title-block-published: "Última actualización:"
   section-title-references: "Bibliografía"
format:
   html:
      embed-resources: true
editor: 
  markdown: 
    wrap: 72
---

::: callout-note
-\> Para el desarrollo de las prácticas, uso un flujo de trabajo que
combina el terminal de Linux (Ubuntu/WSL2) para ejecutar comandos, y un
documento Quarto (en R Studio) para documentar todo. Tanto los comandos,
como los resultados y su posterior análisis están registrados en este
documento para garantizar la trazabilidad y reproducibilidad de la
práctica.
-\>He averiguado una forma de trabajar de manera simultánea
para que el render funcione (en principio): la descarga de programas se
lleva a cabo en el entorno Linux, y para que las órdenes de Bash
funcionen en el entorno de R empleo el comando "system("wsl ...")",
siendo lenguaje de R que le pide al programa mediante "wsl" que use el
entorno de Linux, de manera que lo que haya innstalado en Linux, lo
puede emplear/localizar R.

:::

# Preparación

Para asegurar la reproducibilidad de esta práctica , he verificado que
las herramientas necesarias están correctamente instaladas en mi entorno
de Linux (WSL):

```{bash}
#| echo: true
#| eval: false
needle -help
exonerate -version
muscle -version
wget --version
```

[-No me ha dado error en ninguna de las
herramientas.]{style="color:orange"}

# Objetivos

1.  Practicar los comandos básicos de Bash.
2.  Generar la estructura del cuaderno de prácticas.
3.  Realizar algunos alineamientos básicos.

# Comandos básicos

| Comando | Función |
|----------------------------------|:-------------------------------------|
| pwd | Conocer la dirección absoluta del directorio actual |
| cd .. | Cambiar al directorio superior |
| cd a | Entrar en el directorio "a" |
| cp a b | Crear una copia "b" del archivo "a" |
| mv a b | Renombrar el archivo "a" como "b" |
| mkdir a | Crear el directorio "a" |
| rm a | Eliminar el *archivo* "a" |
| rm -r a | Eliminar el *directorio* "a" y su contenido |
| touch a | Crear el archivo vacío "a" o actualizar su fecha de consulta si ya existía |
| ls -l | Lista los archivos con detalles (tamaño, permisos y fecha) |
| ls -lh | Lo mismo que ls -l pero con unidades de tamaño (KB,MB,GB) |
| file a | Indica información del archivo (tipo de archivo ) |
| cat a | Muestra el contenido completo el archivo en el terminal (no usar para archivos data, compressed, executable o grandes) |
| zcat a | Igual que cat, pero lee archivos comprimidos (.gz) sin descomprimirlos |
| head a | Muestra las primeras 10 líneas de un archivo de texto |
| tail a | Muestra las últimas 10 líneas de un archivo de texto |
| grep "texto" a | Busca "texto" dentro del archivo a |
| zgrep "texto" a | Busca "texto" dentro de un archivo comprimido a |
| less a | Abre el archivo en modo lectura |
| wc -l | Cuenta el número de líneas |

::: {.callout-tip title="Consejo"}
Amplía la tabla modificando el documento fuente.

:::

[-Hecho]{style="color:orange"}

::: {.callout-note icon="false"}
## Ejercicio 1

Escoge un lugar adecuado en el árbol de directorios de tu ordenador para
crear la carpeta que contendrá tu cuaderno de prácticas, en el cual
incluirás tu propia versión de este primer guión. El *cuaderno* será una
**carpeta** entera. Dale un nombre adecuado y genera esta estructura en
su interior usando los comandos de Bash que has aprendido:

```         
├── data
├── doc
└── results
    ├── 2026-01-29
    │   └── README00.Qmd
    ├── 2026-02-03
    ├── 2026-02-10
    ├── 2026-02-17
    ├── 2026-02-24
    ├── 2026-03-03
    ├── 2026-03-10
    ├── 2026-03-24
    ├── 2026-03-31
    ├── 2026-04-15
    ├── 2026-04-21
    ├── 2026-04-28
    └── 2026-05-05
```
:::

[-Carpetas creadas correctamente y siguiendo el patrón README00
(práctica 1), README01 (práctica 2), etc.]{style="color:orange"}

# Alineamiento de pares de secuencia

En los enlaces siguientes encontrarás las secuencias descritas a
continuación:

-   [HumanChr17](https://rest.ensembl.org/sequence/region/human/17:63832000..63843000:1)
    Un fragmento del cromosoma 17 humano.
-   [ChimpChr17](https://rest.ensembl.org/sequence/region/chimpanzee/17:63309800..63321000:1)
    Un fragmento del cromosoma 17 de chimpancé, homólogo al anterior.
-   [HumanSMARCD2](https://www.ebi.ac.uk/ena/browser/api/fasta/AAI36323.1)
    Tránscrito del gen SMARCD2 humano.
-   [ChimpSMARCD2](https://www.ebi.ac.uk/ena/browser/api/fasta/PNJ01291.1)
    Tránscrito del gen SMARCD2 de chimpancé.

El objetivo es alinear los tránscritos a sus respectivos fragmentos
genómicos y comprobar que el alineamiento predice correctamente la
estructura de intrones y exones del gen. Si las herramientas de
[EMBOSS](http://emboss.open-bio.org/) están instaladas, podemos usar los
programas
[`needle`](http://emboss.open-bio.org/rel/rel6/apps/needle.html) o
[`water`](http://emboss.open-bio.org/rel/rel6/apps/water.html) para
realizar el alineamiento desde la linea de órdenes mediante los
algoritmos de Needleman-Wunsch o de Smith-Waterman, respectivamente.
Puedes consultar la ayuda completa de estas herramientas ejecutando
`needle -help -verbose` o `water -help -verbose`. Las órdenes siguientes
descargan dos de las secuencias y las alinean con `needle`, a modo de
ejemplo. El resultado del alineamiento debería guardarse en un archivo
en formato de texto.

```{bash}
#| eval: false
# Sólo queremos ejecutar el código si los resultados no
# están ya disponibles, es decir, si el archivo de salida no existe.
if [ ! -e aln1.txt ]; then
   # Sólo descargaremos las secuencias, si no están ya descargadas.
   if [ ! -e HumanSMARCD2.fa ]; then
      # Con la opción "-O" (letra mayúscula, no número cero) indicamos
      # el nombre del archivo donde queremos guardar la secuencia.
      wget -O HumanSMARCD2.fa https://www.ebi.ac.uk/ena/browser/api/fasta/AAI36323.1
   fi
   if [ ! -e HumanChr17.fa ]; then
      wget -O HumanChr17.fa \
         https://rest.ensembl.org/sequence/region/human/17:63832000..63843000:1?content-type=text/x-fasta
   fi
   # Utilizamos el carácter "\" para que Bash ignore el salto de línea
   # y poder distribuir los argumentos y opciones en más de una línea.
   needle -asequence HumanChr17.fa \
          -bsequence HumanSMARCD2.fa \
          -gapopen 15.0 \
          -gapextend 0.5 \
          -auto \
          -outfile aln1.txt
fi
```

[-Obtenido el archivo aln1.txt]{style="color:orange"} 
# Desafíos

0.  Lee detenidamente las órdenes y los comentarios y asegúrate de
    entenderlos. 
    [Si no existe el archivo aln1.txt-\> descarga los
    archivos de la secuencia y el genoma en caso de que no estén
    descargadas previamente, y empleamos la herramienta needle para un
    alineamiento global.]{style="color:orange"}
1.  Si al ejecutarlas aparece algún mensaje de error, léelo y corrige el
    error. [En el bloque aparecía una errata en el nombre del archivo;
    debería poner HumanSMARCD2.fa cada vez que se escriba para que el
    programa no se confunda de archivo, pero en uno ponía
    HumanaSMARCD2.fa, de manera que se está buscando un archivo que no
    existe.]{style="color:orange"}
2.  Lee la ayuda del programa `needle` e intenta ajustar los parámetros
    para obtener un alineamiento más convincente.

```{bash}
#| eval: false
if [ ! -e aln2.txt ]; then
   if [ ! -e HumanSMARCD2.fa ]; then
      wget -O HumanSMARCD2.fa https://www.ebi.ac.uk/ena/browser/api/fasta/AAI36323.1
   fi
   if [ ! -e HumanChr17.fa ]; then
      wget -O HumanChr17.fa \
         https://rest.ensembl.org/sequence/region/human/17:63832000..63843000:1?content-type=text/x-fasta
   fi
   needle -asequence HumanChr17.fa \
          -bsequence HumanSMARCD2.fa \
          -gapopen 20.0 \
          -gapextend 0.5 \
          -noendweight \
          -auto \
          -outfile aln2.txt
fi
```

```{bash}
#| eval: false
if [ ! -e aln3.txt ]; then
   if [ ! -e HumanSMARCD2.fa ]; then
      wget -O HumanSMARCD2.fa https://www.ebi.ac.uk/ena/browser/api/fasta/AAI36323.1
   fi
   if [ ! -e HumanChr17.fa ]; then
      wget -O HumanChr17.fa \
         https://rest.ensembl.org/sequence/region/human/17:63832000..63843000:1?content-type=text/x-fasta
   fi
   needle -asequence HumanChr17.fa \
          -bsequence HumanSMARCD2.fa \
          -gapopen 15.0 \
          -gapextend 0.3 \
          -noendweight \
          -auto \
          -outfile aln3.txt
fi
```

[-Tras estudiar los ajustes de needle, el mejor ajuste de parámetros que
he encontrado es el correspondiente al archivo "aln3.txt". He añadido
"noendweight" que elimina la penalización por la diferencia de tamaño
entre secuencias a alinear; al tratarse de una comparación entre un
fragmento del cromosoma y un tránscrito, existe una diferencia de tamaño
considerable debido a los intrones y la penalización sería elevada en
caso de poner "yesendweight". También he intentado aumentar la
penalización "gapopen" a 20 para que el alineamiento sea más estricto y
trate de abrir pocos huecos pero de gran longitud (intrones); no
obstante, el resultado obtenido (aln2.txt) presentaba una menor
puntuación (426.0) y una caída en la identidad al 7.0%. Unos ajustes tan
restrictivos impiden que el programa identifique exones cortos,
incluyéndolos como intrones para evitar abrir huecos nuevos. Finalmente,
decidí mantener la apertura en 15.0 pero reducir la extensión a 0.3.
Esta opción permite que los huecos largos (intrones) fluyan mejor sin
penalizar tanto el score. Con esto, la identidad subió al 8.5% (942
coincidencias) y la puntuación mejoró a 1098,4.]{style="color:orange"}

3.  Prueba el programa `water`, para que el alineamiento sea local.

```{bash}
#| eval: false
if [ ! -e aln01.txt ]; then
   if [ ! -e HumanSMARCD2.fa ]; then
      wget -O HumanSMARCD2.fa https://www.ebi.ac.uk/ena/browser/api/fasta/AAI36323.1
   fi
   if [ ! -e HumanChr17.fa ]; then
      wget -O HumanChr17.fa \
         https://rest.ensembl.org/sequence/region/human/17:63832000..63843000:1?content-type=text/x-fasta
   fi
   water -asequence HumanChr17.fa \
          -bsequence HumanSMARCD2.fa \
          -gapopen 15.0 \
          -gapextend 0.5 \
          -auto \
          -outfile aln01.txt
fi
```

[-El alineamiento local ignora las regiones no homólogas de los extremos
y se centra en la región de mayor homología. Al ajustar el gapopen a
15.0, el algoritmo conecta mejor los exones, elevando la identidad al
41.0% y el score a 890. Este porcentaje de identidad en un segmento
específico confirma la localización exacta del gen SMARCD2 dentro del
cromosoma.]{style="color:orange"}

4.  Intenta guardar el alineamiento en formato FASTA.

```{bash}
#| eval: false
if [ ! -e aln3.fasta ]; then
   if [ ! -e HumanSMARCD2.fa ]; then
      wget -O HumanSMARCD2.fa https://www.ebi.ac.uk/ena/browser/api/fasta/AAI36323.1
   fi
   if [ ! -e HumanChr17.fa ]; then
      wget -O HumanChr17.fa \
         https://rest.ensembl.org/sequence/region/human/17:63832000..63843000:1?content-type=text/x-fasta
   fi
   needle -asequence HumanChr17.fa \
          -bsequence HumanSMARCD2.fa \
          -gapopen 15.0 \
          -gapextend 0.3 \
          -noendweight \
          -aformat fasta \
          -auto \
          -outfile aln3.fasta
fi
```

[-Resultado obtenido adecuadamente en formato
FASTA.]{style="color:orange"}

5.  Alinea también el tránscrito de SMARCD2 de chimpancé a su cromosoma.

```{bash}
#| eval: false

if [ ! -e alnchimp0.txt ]; then
   if [ ! -e ChimpSMARCD2.fa ]; then
      wget -O ChimpSMARCD2.fa https://www.ebi.ac.uk/ena/browser/api/fasta/PNJ01291.1
   fi
   if [ ! -e ChimpChr17.fa ]; then
      wget -O ChimpChr17.fa \
         https://rest.ensembl.org/sequence/region/chimpanzee/17:63309800..63321000:1?content-type=text/x-fasta
   fi
   water  -asequence ChimpChr17.fa \
          -bsequence ChimpSMARCD2.fa \
          -gapopen 15.0 \
          -gapextend 0.3 \
          -auto \
          -outfile alnchimp0.txt
fi
```

[-He realizado un alineamiento local ya que este buscará la región de
máxima homología entre el tránscrito y el fragmento de cromosoma,
ignorando el resto de la secuencia. \*Importante: para descargar la
secuencia ChimpChr17.fa añadir al final de esta
"?content-type=text/x-fasta", o no podrá ser
leída.]{style="color:orange"}

6.  Alinea también los dos fragmentos cromosómicos. 

```{bash}
#| eval: false
if [ ! -e alncromo.txt ]; then
   if [ ! -e HumanChr17.fa ]; then
      wget -O HumanChr17.fa \  
      https://rest.ensembl.org/sequence/region/human/17:63832000..63843000:1?content-type=text/x-fasta
   fi
   if [ ! -e ChimpChr17.fa ]; then
      wget -O ChimpChr17.fa \
         https://rest.ensembl.org/sequence/region/chimpanzee/17:63309800..63321000:1?content-type=text/x-fasta
   fi
   needle -asequence ChimpChr17.fa \
          -bsequence ChimpSMARCD2.fa \
          -gapopen 15.0 \
          -gapextend 0.3 \
          -auto \
          -outfile alncromo.txt
fi
```

[-En este caso, he realizado un alineamiento global ya que se están
comparando dos fragmentos de cromosoma de longitud
similar.]{style="color:orange"}

Para alinear tránscritos o incluso proteínas a un genoma de referencia,
es mejor usar el programa `exonerate` [@Slater2005], que puede aplicar
los parámetros más adecuados para este tipo de tarea. Puedes leer la
documentación de `exonerate` mediante las órdenes `man exonerate` o
`exonerate --help`. También existe [documentación online sobre este
programa](https://www.animalgenome.org/bioinfo/resources/manuals/exonerate/index.html).
En el bloque siguiente repetimos el mismo alineamiento que antes, con
`exonerate`.

```{bash}
#| eval: true
#| output: true
#| error: true

if [ ! -e HumanSMARCD2.fa ]; then
   wget -O HumanSMARCD2.fa https://www.ebi.ac.uk/ena/browser/api/fasta/AAI36323.1
fi
if [ ! -e HumanChr17.fa ]; then
   wget -O HumanChr17.fa \
      https://rest.ensembl.org/sequence/region/human/17:63832000..63843000:1?content-type=text/x-fasta
fi
exonerate --model est2genome HumanSMARCD2.fa HumanChr17.fa
```

En este caso, el alineamiento resultante no se ha enviado a un archivo,
sino al *standard output*, que Quarto recoge y presenta en este mismo
documento. Por eso, no hemos condicionado la ejecución.

::: {.callout-note icon="false"}
## Desafío

¿Cómo puedes enviar el resultado de `exonerate` a un archivo?

:::

```{bash}
#| eval: true
#| output: true
#| error: true

if [ ! -e HumanSMARCD2.fa ]; then
   wget -O HumanSMARCD2.fa https://www.ebi.ac.uk/ena/browser/api/fasta/AAI36323.1
fi
if [ ! -e HumanChr17.fa ]; then
   wget -O HumanChr17.fa \
      https://rest.ensembl.org/sequence/region/human/17:63832000..63843000:1?content-type=text/x-fasta
fi
exonerate --model est2genome HumanSMARCD2.fa HumanChr17.fa > exonerate.txt
```

[-Se añade al final del comando "\>
nombre_del_archivo.txt".]{style="color:orange"}

# Apéndice. Alineamientos múltiples

Un programa muy popular para alineamiento de múltiples secuencias es
[`muscle`](https://drive5.com/muscle/) [@Edgar2022]. Suponiendo que está
instalado, vamos a probarlo con una colección de secuencias que
pertenecen a la familia
[PF00009](https://www.ebi.ac.uk/interpro/entry/pfam/PF00009/):

```{bash}
if [ ! -e PF00009.fa ]; then
   wget -O PF00009.fa https://raw.githubusercontent.com/rcedgar/balifam/refs/heads/main/balifam100/in/PF00009.100
fi

if [ ! -e PF00009.afa ]; then
   muscle -align PF00009.fa -output PF00009.afa
fi
```

Para visualizar el alineamiento, podemos usar la función `BrowseSeqs()`,
del paquete `DECIPHER` en el entorno de R. Esta función nos permite
enviar el alineamiento a un archivo HTML, que puede abrirse en una
ventana nueva. Si estamos compilando un documento HTML, podemos
incorporar el alineamiento en el mismo documento mediante la función
`includeHTML()` del paquete `htmltools`, al precio de aumentar
considerablemente su tamaño.

```{r}
#| messages: false
#| warning: false

library('htmltools')
library('DECIPHER')
PF00009 <- readAAStringSet('PF00009.afa')
BrowseSeqs(PF00009, htmlFile = 'PF00009.html', openURL = FALSE)
includeHTML('./PF00009.html')
```
[-Me pide una versión de R que no tengo para obtener el paquete DECIPHER.]{style="color:red"}


# Bibliografía
